routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();


Route::get('/', ['as'=>'home', 'uses'=>'HomeController@index']);
Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');
Route::get('/live_search/category', 'LiveSearch@category')->name('live_search.category');
Route::resource('posts','PostController');
Route::resource('categories','CategoryController');


Route::group(['middleware' => ['auth'],'guard_name' => App\Permission::SUPER_ADMIN, ], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::get('/users/{id}/restore', 'UserController@restore')->name('user.restore');
    Route::get('/users/{id}/forcedelete', 'UserController@forcedelete')->name('user.forcedelete');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id','category_id','name', 'test_text', 'post_id'
    ];

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Category;
use App\Post;
use Illuminate\Http\Request;
use App\Http\Requests;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;
use App\Permission;

class PostController extends Controller
{

    /**
     * Display a listing of the resource.
     */
    function __construct()
    {
        $this->middleware('permission:'.Permission::SUPER_ADMIN, ['only' => ['create','store', 'edit', 'update', 'destroy']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->paginate(5);
        return view('posts.index',compact('posts'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::pluck('name', 'id');
        return view('posts.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required|max:255',
            'test_text' => 'required',
            'text' => 'required',
            'feature_image' => 'image|mimes:jpg,png,jpeg,gif,svg|max:2048',
        ]);

        $data = $request->all();
        $fileName = null;
        if (request()->hasFile('feature_image')) {
            $file = request()->file('feature_image');
            $fileName =  time() ."-". md5($file->hashName()). "." . $file->getClientOriginalExtension();
            $loaction = public_path('uploads/'.$fileName);
            Image::make($file)->resize(1920,1080)->save($loaction);
        }

        $post = new Post;
        $post->user_id = Auth::id();
        $post->category_id = $data['category'];
        $post->name = $data['name'];
        $post->test_text = $data['test_text'];
        $post->image = $fileName;
        $post->save();

        $answers = $data['text'];
        foreach ( $answers as $key=>$answer ) {
                Answer::create([
                    'post_id' => $post->id,
                    'right' => ( $request['answer_true_'.++$key] ) ? 1 : 0,
                    'text' => $answer,
                    'description' => $answer
                ]);
        }


        return redirect()->route('posts.index')
            ->with('success','Post created successfully.');

    }

    /**
     * Display the specified resource.
     *
     * @param Post $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::pluck('name', 'id');
        return view('posts.edit',compact(['post', 'categories']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Post $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $answersToDelete = $post->answers;

        foreach ($answersToDelete as $answer) {
            $answer->delete();
        }

        request()->validate([
            'name' => 'required|max:255',
            'test_text' => 'required',
            'text' => 'required',
        ]);

        $data = $request->all();

        $fileName = null;

        if (request()->hasFile('feature_image')) {
            $file = request()->file('feature_image');
            $fileName =  time() ."-". md5($file->hashName()). "." . $file->getClientOriginalExtension();
            $loaction = public_path('uploads/'.$fileName);
            Image::make($file)->resize(1920,1080)->save($loaction);
        }


        $answers = $data['text'];

        $answers = $data['text'];
        foreach ( $answers as $key=>$answer ) {
            Answer::create([
                'post_id' => $post->id,
                'right' => ( $request['answer_true_'.++$key] ) ? 1 : 0,
                'text' => $answer,
                'description' => $answer
            ]);
        }

        $post->category_id = $request['category'];
        $post->name = $request['name'];
        $post->test_text = $request['test_text'];
        $post->image = $fileName;
        $post->save();

        return redirect()->route('posts.index')
            ->with('success','Post updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Post $post
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route('posts.index')
            ->with('success','Post deleted successfully');
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New post</h2>
            </div>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::open(array('route' => 'posts.store', 'files'=>true)) !!}
        @csrf
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Detail:</strong>
                        <textarea class="form-control" style="height:150px" name="test_text" placeholder="Detail"></textarea>
                    </div>
                <div class="form-group answers-blocks">
                    <div data-block="1" class="answer-block row mt-3">
                            <div class="col-1 center-items">
                                <input type="checkbox" class="checkbox" name="answer_true_1" >
                            </div>
                            <div class="col">
                                <input type="text" class="form-control" name="text[]" placeholder="Answer" required>
                            </div>
                        <div class="col-1 center-items">
                            <button type="button" class="close" data-remove="block-1" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        </div>
                        <div data-block="2" class="answer-block row mt-3">
                            <div class="col-1 center-items">
                                <input type="checkbox" class="checkbox" name="answer_true_2" >
                            </div>
                            <div class="col">
                                <input type="text" class="form-control" name="text[]" placeholder="Answer" required>
                            </div>
                            <div class="col-1 center-items">
                                <button type="button" class="close" data-remove="block-2" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                    </div>
                </div>
                <div class="text-center">
                    <button id="add-answer" type="button" class="btn btn-primary text-center" data-toggle="button" aria-pressed="false" autocomplete="off">
                        Add Answer
                    </button>
                </div>
                <div class="select-container">
                    {{ Form::select('category', $categories, $categories->pluck('name'), ['class' => 'form-control'])}}
                </div>

                <div class="form-group mt-3">
                    <label for="feature_image" class="strong">Set the image(optional)</label><br>
                    {{ Form::file('feature_image')}}
                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>


    {!! Form::close() !!}


@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit post</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('posts.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('posts.update',$post->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $post->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea class="form-control" style="height:150px" name="test_text" placeholder="Detail">{{ $post->test_text }}</textarea>
                </div>
            </div>
        </div>
        <div class="form-group answers-blocks">
            @foreach($post->answers as $key=>$answer)
                <div data-block="{{++$key}}" class="answer-block row block-{{$key}}">
                    <div class="col-1 center-items">
                        <input type="checkbox" class="checkbox" name="answer_true_{{$key}}"
                               @if($answer->right == 1)
                               checked
                            @endif
                        >
                    </div>
                    <div class="col">
                        <input type="text" class="form-control" name="text[]" value="{{$answer->text}}" required>
                    </div>
                    <div class="col-1 center-items">
                        <button type="button" class="close" data-remove="block-{{$key}}" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            @endforeach

        </div>
        <div class="text-center">
            <button id="add-answer" type="button" class="btn btn-primary text-center" data-toggle="button" aria-pressed="false" autocomplete="off">
                Add Answer
            </button>
        </div>
        <div class="select-container">
            {{ Form::select('category', $categories, $categories->pluck('name'), ['class' => 'form-control'])}}
        </div>
        <div class="form-group mt-3">
            <label for="feature_image" class="strong">Set the image(optional)</label><br>
            {{ Form::file('feature_image')}}
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>


@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Posts</h2>
            </div>
            <div class="pull-right">
                @can(App\Permission::SUPER_ADMIN)
                    <a class="btn btn-success" href="{{ route('posts.create') }}"> Create New Post</a>
                @endcan
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Category</th>
            <th>Name</th>
            <th>Details</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($posts as $post)
            <tr>
                <td>{{ ++$i }}</td>
                @if($post->category)

                        <td ><a href="{{route('categories.show',$post->category->id)}}">{{ $post->category->name }}</a></td>

                @endif
                <td width="200px">{{ $post->name }}</td>
                <td>{{ $post->test_text }}</td>
                <td>
                    <form action="{{ route('posts.destroy',$post->id) }}" method="POST">
                        <a class="btn btn-info" href="{{ route('posts.show',$post->id) }}">Show</a>
                        @can(App\Permission::SUPER_ADMIN)
                            <a class="btn btn-primary" href="{{ route('posts.edit',$post->id) }}">Edit</a>
                        @endcan
                        @csrf
                        @method('DELETE')
                        @can(App\Permission::SUPER_ADMIN)
                            <button type="submit" class="btn btn-danger">Delete</button>
                        @endcan
                    </form>
                </td>
            </tr>
        @endforeach
    </table>


    {!! $posts->links() !!}


@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')


@section('content')

    <div class="row">
        <div class="col-md-12">

            <div class="card mb-5">
                <div class="card-header">
                    <h3 class="block text-center">{{$post->name}}</h3>
                    <span class="badge badge-dark inline f14">
                        @if($post->category)
                            <a href="{{route('categories.show',$post->category->id) }}">{{$post->category->name}}</a>
                        @endif
                    </span>
                </div>
                <div class="card-body">
                    @foreach($post->answers as $answer)
                        @if($answer->right == 1)
                            <div class="alert alert-success">{{ $answer->text  }}</div>
                        @else
                            <div class="alert alert-light">{{ $answer->text  }}</div>
                        @endif
                    @endforeach
                    @if($post->image)
                        <img src="{{asset('uploads/'.$post->image)}}" alt="post_image" class="align-right img-fluid">
                    @endif
                </div>
            </div>


        </div>
    </div>
@endsection