routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();


Route::get('/', ['as'=>'home', 'uses'=>'HomeController@index']);
Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');
Route::get('/live_search/category', 'LiveSearch@category')->name('live_search.category');
Route::resource('posts','PostController');
Route::resource('categories','CategoryController');


Route::group(['middleware' => ['auth'],'guard_name' => App\Permission::SUPER_ADMIN, ], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::get('/users/{id}/restore', 'UserController@restore')->name('user.restore');
    Route::get('/users/{id}/forcedelete', 'UserController@forcedelete')->name('user.forcedelete');
});

app/Category.php
<?php

namespace App;

use App\Observers\CategoryObserver;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name', 'description', 'parent_id'
    ];
    protected $dispatchesEvents = [
        'deleted' => CategoryObserver::class,
    ];
    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    public function posts()
    {
        return $this->hasMany(Post::class, 'category_id');
    }

    public function getParentsAttribute()
    {
        $parents = collect([]);

        $parent = $this->parent();

        while (!is_null($parent)) {
            $parents->push($parent);
            $parent = $parent->parent();
        }

        return $parents;
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;
use App\Permission;
class CategoryController extends Controller
{
    /**
     * CategoryController constructor.
     */
    function __construct()
    {
        $this->middleware('permission:'.Permission::SUPER_ADMIN, ['only' => ['create','store', 'index', 'edit', 'update', 'destroy']]);
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $categories = Category::latest()->paginate(5);
        return view('categories.index',compact('categories'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * @param Category $category
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Category $category)
    {
        return view('categories.show',compact('category'))
            ->with('i', (request()->input('page', 1) - 1) * 5);;
    }

    /**
     * @param Category $category
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Category $category)
    {
        $categories = Category::pluck('name', 'id');
        return view('categories.edit',compact(['category', 'categories']));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $categories = Category::pluck('name', 'id');
        return view('categories.create', compact('categories'));
    }


    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required|max:255',
            'description' => 'required',
        ]);
        $data = $request->all();
        $category = Category::create($data);
        return redirect()->route('categories.index')
            ->with('success','Post created successfully.');

    }


    /**
     * @param Request $request
     * @param Category $category
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Category $category)
    {
        request()->validate([
            'name' => 'required|max:255',
            'description' => 'required',
        ]);
        $data = $request->all();

        $category->update([
            'parent_id' => $data['parent_id'],
            'name' => $data['name'],
            'description' => $data['description']
        ]);

        return redirect()->route('categories.index')
            ->with('success','Category updated successfully.');
    }

    /**
     * @param Category $category
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Category $category)
    {

        $category->delete();

        return redirect()->route('categories.index')
            ->with('success','Category deleted successfully');
    }

}

resources/views/categories/create.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New post</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('categories.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('categories.store') }}" method="POST">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Category Title:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Category Description:</strong>
                    <textarea class="form-control" style="height:150px" name="description" placeholder="Detail"></textarea>
                </div>
                <select name="parent_id" class="form-control">
                    <option value="0">No parent</option>
                @foreach ($categories as $key => $name)
                        <option value="{{$key}}">{{$name}}</option>
                @endforeach
                </select>
            </div>


            <div class="col-xs-12 col-sm-12 col-md-12 text-center mt-3">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>


    </form>


@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New post</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('categories.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('categories.update', $category->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Category Title:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name" value="{{$category->name}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Category Description:</strong>
                    <textarea class="form-control" style="height:150px" name="description" placeholder="Detail">{{$category->description}}</textarea>
                </div>

                <select name="parent_id" class="form-control">
                    <option value="0">No parent</option>
                    @foreach ($categories as $key => $name)
                        <option value="{{$key}}">{{$name}}</option>
                    @endforeach
                </select>

            </div>


            <div class="col-xs-12 col-sm-12 col-md-12 text-center mt-3">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>


    </form>


@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Posts</h2>
            </div>
            <div class="pull-right">
                @can(App\Permission::SUPER_ADMIN)
                    <a class="btn btn-success" href="{{ route('categories.create') }}"> Create New Category</a>
                @endcan
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Parent</th>
            <th>Name</th>
            <th>Details</th>
        </tr>
        @foreach ($categories as $category)
            <tr>
                <td>{{ ++$i }}</td>
                @if( $category->parent )
                <td><a href="{{route('categories.show',$category->parent->id)}}">{{ $category->parent->name }}</a></td>
                @else
                    <td></td>
                @endif
                <td><a href="{{route('categories.show',$category->id)}}">{{ $category->name }}</a></td>
                <td>{{ $category->description }}</td>
            </tr>
        @endforeach
    </table>


    {!! $categories->links() !!}


@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <form action="{{ route('categories.destroy',$category->id) }}" method="POST">
                @can(App\Permission::SUPER_ADMIN)
                    <a class="btn btn-primary" href="{{ route('categories.edit',$category->id) }}">Edit</a>
                @endcan
                @csrf
                    @if( $category->id != 1 )
                @method('DELETE')
                @can(App\Permission::SUPER_ADMIN)
                    <button type="submit" class="btn btn-danger">Delete</button>
                @endcan
                        @endif
            </form>
        </div>
    </div>
    <h1>{{$category->name}}</h1>
    @if($category->parent)
        @if($category->parent->id !== $category->id && $category->parent_id !== 0)
            <h2>Parent: <a href="{{route('categories.show', $category->parent->id)}}">{{$category->parent->name}}</a></h2>
        @endif
    @endif
    <h2>Questions:</h2>
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Details</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($category->posts as $post)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $post->name }}</td>
                <td>{{ $post->test_text }}</td>
                <td>
                    <form action="{{ route('posts.destroy',$post->id) }}" method="POST">
                        <a class="btn btn-info" href="{{ route('posts.show',$post->id) }}">Show</a>
                        @can(App\Permission::SUPER_ADMIN)
                            <a class="btn btn-primary" href="{{ route('posts.edit',$post->id) }}">Edit</a>
                        @endcan


                        @csrf
                        @method('DELETE')

                        @can(App\Permission::SUPER_ADMIN)
                            <button type="submit" class="btn btn-danger">Delete</button>
                        @endcan

                    </form>
                </td>
            </tr>
        @endforeach
    </table>




@endsection